spring:
  banner:
    location: banner.txt
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/learnspring?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driverClassName: com.mysql.cj.jdbc.Driver
    username: guest
    password: 123456
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
mybatis:
  #config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
